import json
import os
from datetime import datetime
from intelligence_extractor import IntelligenceExtractor
from session_aggregator import aggregate_session
from ollama import Client

# Initialize Ollama client
ollama_client = Client(host='http://localhost:11434')

# Load product catalog and policies
script_dir = os.path.dirname(__file__)
catalog_path = os.path.join(script_dir, '..', 'data', 'product_catalog.json')
policies_path = os.path.join(script_dir, '..', 'data', 'policies.json')

with open(catalog_path, 'r', encoding='utf-8') as f:
    PRODUCT_CATALOG = json.load(f)

with open(policies_path, 'r', encoding='utf-8') as f:
    POLICIES = json.load(f)

# Only user messages - assistant responses will be generated by LLM
SHOPPER_MESSAGES = [
    {
        "turn": 1,
        "user": "Show me your winter hoodies"
    },
    {
        "turn": 2,
        "user": "What's the difference between the two hoodies?"
    },
    {
        "turn": 3,
        "user": "The Premium one is expensive. Is it worth it?"
    },
    {
        "turn": 4,
        "user": "I'm worried it won't fit me. I'm 6 feet tall."
    },
    {
        "turn": 5,
        "user": "Still not 100% sure about this."
    },
    {
        "turn": 6,
        "user": "How long does shipping take?"
    },
    {
        "turn": 7,
        "user": "I want to buy the Premium Waterproof Hoodie in size L."
    },
    {
        "turn": 8,
        "user": "idk man feels pricey tbh"
    },
    {
        "turn": 9,
        "user": "size chart confusing 😕"
    },
    {
        "turn": 10,
        "user": "umm still not sure"
    }
]

GROUNDED_SYSTEM_PROMPT = """You are a shopper-facing assistant for an ecommerce store.

Your primary responsibility is to respond to shoppers using ONLY the factual information provided to you.

You MUST NOT invent, assume, or imply any information that is not explicitly present in the provided data.

You are NOT allowed to:
- Invent warranties, guarantees, or policies
- Invent product features or benefits
- Invent tools, charts, comparisons, or services
- Exaggerate or add marketing claims
- Mention anything outside the provided data

If information is missing, you MUST say you do not have that information.

OBJECTION HANDLING GUIDELINES:

IF objection == "price_sensitivity":
  Explain price using product features or materials ONLY.

IF objection == "fit_uncertainty":
  Mention fit type and available sizes ONLY.

IF objection == "delivery_returns_risk":
  Mention only return window and shipping time from policies.

IF objection == "choice_overload":
  Recommend ONE product based on use_case overlap.

IF objection == "none":
  Provide straightforward helpful information.

HARD CONSTRAINTS:
- Do NOT mention warranty unless policy warranty.available == true
- Do NOT mention free returns unless policy returns.free_returns == true
- Do NOT mention shipping speed unless explicitly stated
- Do NOT invent charts, guides, or tools
- Do NOT say "best seller", "top rated", or similar claims

If any information is missing, politely say it is not available.

Return ONLY the assistant's reply text (1-2 sentences). No JSON, no markdown, no explanations."""

def generate_assistant_response(user_message: str, intent: str, objection: str) -> str:
    """Generate grounded assistant response using LLM with full context"""
    
    # Format product data (relevant products only)
    relevant_products = [p for p in PRODUCT_CATALOG['products'] if p['category'] == 'hoodies']
    
    prompt = f"""{GROUNDED_SYSTEM_PROMPT}

SHOPPER MESSAGE:
{user_message}

DETECTED INTENT:
{intent}

DETECTED OBJECTION:
{objection}

PRODUCT DATA:
{json.dumps(relevant_products, indent=2)}

POLICY DATA:
{json.dumps(POLICIES, indent=2)}

Generate the assistant's response:"""
    
    response = ollama_client.generate(
        model='llama3.1:latest',
        prompt=prompt,
        stream=False,
        options={
            'temperature': 0.3,
            'top_p': 0.9,
            'num_predict': 100
        }
    )
    
    return response['response'].strip()


def run_session_demo(use_llm: bool = False):
    """
    Run complete session intelligence extraction and aggregation.
    Generates realistic assistant responses using LLM.
    
    Args:
        use_llm: If True, use LLM classifier. If False, use stub.
    """
    classifier_mode = "LLM (LLaMA 3.1)" if not use_llm else "Stub (Keyword-based)"
    
    print("=" * 80)
    print(f"LEVEL 4 DEMO: SESSION AGGREGATION (GROUNDED RESPONSES)")
    print(f"Classifier: {classifier_mode}")
    print("=" * 80)
    
    # Initialize extractor
    extractor = IntelligenceExtractor(use_stub=use_llm)
    
    # Collect turn-level intelligence
    turn_intelligence = []
    conversation = []
    
    print("\n" + "=" * 80)
    print("PART 1: TURN-BY-TURN INTELLIGENCE WITH GROUNDED RESPONSES")
    print("=" * 80)
    
    for msg_obj in SHOPPER_MESSAGES:
        print(f"\n{'─'*80}")
        print(f"TURN {msg_obj['turn']}")
        print(f"{'─'*80}")
        print(f"👤 Shopper: {msg_obj['user']}")
        
        # Step 1: Get preliminary intent/objection from user message
        print(f"🧠 Detecting intent/objection...")
        preliminary_intel = extractor.extract_intelligence(msg_obj['user'], "")
        detected_intent = preliminary_intel['intent']
        detected_objection = preliminary_intel['objection']
        
        # Step 2: Generate grounded assistant response using detected intent/objection
        print(f"🤖 Assistant: [Generating grounded response...]")
        assistant_response = generate_assistant_response(
            msg_obj['user'], 
            detected_intent, 
            detected_objection
        )
        print(f"🤖 Assistant: {assistant_response}")
        
        # Step 3: Final classification on full conversation pair
        intelligence = extractor.extract_intelligence(
            msg_obj['user'],
            assistant_response
        )
        
        print(f"\n📊 Intelligence:")
        print(f"   Intent: {intelligence['intent']}")
        print(f"   Objection: {intelligence['objection']}")
        print(f"   Stage: {intelligence['purchase_stage']}")
        print(f"   Sentiment: {intelligence['sentiment']}")
        
        turn_intelligence.append(intelligence)
        conversation.append({
            "turn": msg_obj['turn'],
            "user": msg_obj['user'],
            "assistant": assistant_response,
            "intelligence": intelligence
        })
    
    # Aggregate session
    print("\n" + "=" * 80)
    print("PART 2: SESSION-LEVEL AGGREGATION")
    print("=" * 80)
    
    session_summary = aggregate_session(turn_intelligence)
    
    print(f"\n📈 SESSION SUMMARY (Final Business Intelligence)")
    print("─" * 80)
    print(json.dumps(session_summary, indent=2))
    
    # Interpret results
    print("\n" + "=" * 80)
    print("BUSINESS INSIGHTS")
    print("=" * 80)
    
    print(f"\n✓ Primary Intent: {session_summary['primary_intent']}")
    print(f"  → Shopper's main goal across the session")
    
    print(f"\n✓ Dominant Objection: {session_summary['dominant_objection']}")
    print(f"  → Main blocker that almost prevented conversion")
    
    print(f"\n✓ Journey Path: {' → '.join(session_summary['journey_path'])}")
    print(f"  → How the shopper navigated from discovery to decision")
    
    print(f"\n✓ Funnel Outcome: {session_summary['funnel_outcome'].upper()}")
    print(f"  → Final conversion state")
    
    print(f"\n✓ Conversion Likelihood: {session_summary['conversion_likelihood'].upper()}")
    print(f"  → Probability estimate based on session behavior")
    
    print(f"\n✓ Recommended Follow-Up: {session_summary['recommended_followup']}")
    print(f"  → Actionable next step to address objection")
    
    # Business action recommendations
    print("\n" + "=" * 80)
    print("ACTIONABLE RECOMMENDATIONS")
    print("=" * 80)
    
    if session_summary['funnel_outcome'] == 'converted':
        print("\n🎯 Conversion Achieved!")
        print("   • Send order confirmation email")
        print("   • Upsell complementary products")
        if session_summary['dominant_objection'] != 'none':
            print(f"   • Address {session_summary['dominant_objection']} in post-purchase messaging")
    
    elif session_summary['funnel_outcome'] == 'undecided':
        print("\n⚠️  Shopper is Undecided")
        print(f"   • {session_summary['recommended_followup']}")
        print("   • Send cart reminder email in 1 hour")
        print("   • Offer live chat support")
    
    else:  # dropped
        print("\n❌ Shopper Dropped Off")
        print(f"   • {session_summary['recommended_followup']}")
        print("   • Retarget with ads addressing objection")
        print("   • Send follow-up email with solution")
    
    print("\n" + "=" * 80)
    print("DEMO COMPLETE")
    print("=" * 80)
    print(f"\nTotal Turns: {len(turn_intelligence)}")
    print(f"Session Duration: {len(turn_intelligence)} turns (realistic ecommerce conversation)")
    
    # Save session results to file
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    data_dir = os.path.join(os.path.dirname(__file__), '..', 'data')
    os.makedirs(data_dir, exist_ok=True)
    
    output_file = os.path.join(data_dir, f"session_summary_{timestamp}.json")
    
    result = {
        "timestamp": datetime.now().isoformat(),
        "classifier_mode": classifier_mode,
        "response_generation": "Grounded (No Hallucination)",
        "total_turns": len(turn_intelligence),
        "conversation": conversation,
        "session_summary": session_summary
    }
    
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(result, indent=2, fp=f)
    
    print(f"\n💾 Results saved to: {os.path.abspath(output_file)}")
    print(f"Business Value: Actionable insights from grounded, hallucination-safe conversation")
    
    return session_summary


if __name__ == "__main__":
    # Run demo with LLM classifier (production mode)
    print("\n🚀 Running with LLM classifier (LLaMA 3.1)...\n")
    run_session_demo(use_llm=False)
    
    # Optionally run with stub (faster for testing)
    # print("\n\n🚀 Running with STUB classifier (fast mode)...\n")
    # run_session_demo(use_llm=True)
